address_book/urls.py
from django.urls import path, re_path

from address_book import views
from address_book.views import AddressBookList, OnePerson, OnePersonCreate, OnePersonEdit, OnePersonDelete

app_name = 'address_book'

urlpatterns = [
    path('', AddressBookList.as_view(), name='home'),
    re_path(r'^filtered/(?P<mystr>.+)/$', views.get_filter_book, name='home-filtered'),
    path('person/<int:pk>/', OnePerson.as_view(), name='person-view'),
    path('person_edit/<int:pk>/', OnePersonEdit.as_view(), name='person-edit'),
    path('create/', OnePersonCreate.as_view(), name='person-create'),
    path('person_delete/<int:pk>/', OnePersonDelete.as_view(), name='person-delete')
]

home_task/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from home_task import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('address_book.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

address_book/models.py
from django.db import models
from django.core.validators import RegexValidator


class Person(models.Model):
    first_name = models.CharField(max_length=100, unique=True)
    last_name = models.CharField(max_length=100, unique=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    street = models.CharField(max_length=100, null=True, blank=True)
    url_address = models.URLField(null=True, blank=True)
    phone_number_regex = RegexValidator(regex=r'^\+?1?\d{8,15}$')
    phone_number = models.CharField(validators=[phone_number_regex],
                                    max_length=16, unique=True, blank=True, null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f'{self.last_name} {self.first_name}'

address_book/forms.py
from django import forms


class FilterForm(forms.Form):
    text = forms.CharField(max_length=100, required=True)

address_book/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views import generic

from address_book.forms import FilterForm
from address_book.models import Person


class AddressBookList(generic.ListView):
    model = Person
    template_name = 'address_book/base.html'

    def get_context_data(self, *args, **kwargs):
        context = super(AddressBookList, self).get_context_data(**kwargs)
        context['form'] = FilterForm
        return context

    @staticmethod
    def post(request):
        form = FilterForm(request.POST)
        return redirect('address_book:home-filtered', mystr=form.data['text'])


def get_filter_book(request, mystr):
    queryset = Person.objects.filter(
        Q(first_name__contains=mystr) | Q(last_name__contains=mystr) |
        Q(country__contains=mystr) | Q(city__contains=mystr) |
        Q(street__contains=mystr) | Q(url_address__contains=mystr)
    )
    if not queryset:
        message = f'Ничего не найдено по запросу "{mystr}".'
        return render(request, 'address_book/filter_search.html', context={'message': message})
    return render(request, 'address_book/filter_search.html', context={'object_list': queryset})


class OnePerson(generic.DetailView):
    model = Person
    template_name = 'address_book/one_person.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get(self.pk_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            obj = "Запись не найдена."
            return obj
        return obj


class OnePersonCreate(generic.CreateView):
    model = Person
    template_name = 'address_book/create_person.html'
    fields = ('first_name', 'last_name', 'country', 'city', 'street',
              'url_address', 'phone_number', 'image')
    success_url = '/'


class OnePersonEdit(generic.UpdateView):
    model = Person
    template_name = 'address_book/edit_person.html'
    fields = ('first_name', 'last_name', 'country', 'city', 'street',
              'url_address', 'phone_number', 'image')
    success_url = '/'


class OnePersonDelete(generic.DeleteView):
    model = Person
    template_name = 'address_book/confirm_delete.html'
    success_url = '/'

address_book/templates/address_book/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Адресная книга</title>{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'address_book/style.css' %}">
</head>
<body>
{% block content %}

{% if object_list %}
<div class="container w-50 mt-2">
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-outline-dark w-50 flex-end m-2">Поиск</button>
  </form>
  <div class="table-responsive">
    <h2 class="text text-dark text-center mt-2 pb-2">Адресная книга</h2>
    <a class="btn btn-success mb-2 text " href="{% url 'address_book:person-create'  %}">Создать контакт</a>
    <table class="table table-sm table-secondary table-striped table-bordered text-center align-middle ">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Имя</th>
          <th scope="col">Фамилия</th>
          <th scope="col">Детальная информация</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
        <tr>
          <th scope="row">{{ forloop.counter}}</th>
          <td>{{ object.first_name }}</td>
          <td>{{ object.last_name }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'address_book:person-view' pk=object.pk %}">Просмотреть</a>
                <a class="btn btn-warning" href="{% url 'address_book:person-edit' pk=object.pk %}">Редактировать</a>
                <a class="btn btn-danger" href="{% url 'address_book:person-delete' pk=object.pk %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% else %}
<div class="container w-50 mt-2">
    <h2 class="text text-dark text-center mt-2 pb-2">Адресная книга</h2>
    <a class="btn btn-success mb-2 text " href="{% url 'address_book:person-create'  %}">Создать контакт</a>
    <h2 class="text text-dark text-center mt-2 pb-2">Пока записей нет.</h2>
</div>
{% endif %}
{% endblock %}
</body>
</html>

address_book/templates/address_book/confirm_delete.html
{% extends 'address_book/base.html' %}
{% block title %}
<title>Удаление контакта номер {{ object.pk }}</title>
{% endblock %}
{% block content %}
<div class="container d-flex align-items-center flex-column justify-content-center " style="height:100%">
  <form class="border border-rounded border-secondary border-3 p-3 bg-secondary" method="post">
    {% csrf_token %}
    <p>Вы уверены что хотите удалить запись "{{ object }}"?</p>
    <div class="d-flex justify-content-evenly">
      <button type="submit" class="btn btn-danger">Удалить</button>
      <a class="btn btn-dark" href="{% url 'address_book:home' %}">Вернуться</a>
    </div>
  </form>
</div>
{% endblock %}

address_book/templates/address_book/create_person.html
{% extends 'address_book/base.html' %}
{% block title %}
<title>Создание контакта</title>
{% endblock %}
{% block content %}
<div class="container">
  <a class="btn btn-outline-dark" href="{% url 'address_book:home'%}"><- Вернуться на главную страницу</a>
  <form class="mx-auto border border-3 border-secondary rounded bg-secondary text-white bg-gradient bg-opacity-75"
        id="create_form" method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.as_table }}
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-outline-dark w-50 flex-end m-2">Создать</button>
    </div>
  </form>
</div>
{% endblock %}

address_book/templates/address_book/edit_person.html
{% extends 'address_book/base.html' %}
{% block title %}
<title>Редактирование контакта номер {{ object.pk }}</title>
{% endblock %}
{% block content %}
<div class="container">
  <a class="btn btn-outline-dark" href="{% url 'address_book:home'%}"><- Вернуться на главную страницу</a>
  <form class="mx-auto border border-3 border-secondary rounded bg-secondary text-white bg-gradient bg-opacity-75"
      method="post" id="create_form" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.as_table }}
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-outline-dark w-50 flex-end m-2">Отредактировать</button>
    </div>
  </form>
</div>
{% endblock %}

address_book/templates/address_book/filter_search.html
{% extends 'address_book/base.html' %}
{% block title %}
<title>TITLE</title>
{% endblock %}
{% block content %}
{% if object_list %}
<div class="container w-50 mt-2">
  <a class="btn btn-outline-dark" href="{% url 'address_book:home'%}"><- Вернуться на главную страницу</a>
  <div class="table-responsive">
    <h2 class="text text-dark text-center mt-2 pb-2">Адресная книга</h2>
    <a class="btn btn-success mb-2 text " href="{% url 'address_book:person-create'  %}">Создать контакт</a>
    <table class="table table-sm table-secondary table-striped table-bordered text-center align-middle ">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Имя</th>
          <th scope="col">Фамилия</th>
          <th scope="col">Детальная информация</th>
        </tr>
      </thead>
      <tbody>
            {% for object in object_list %}
        <tr>
          <th scope="row">{{ forloop.counter}}</th>
          <td>{{ object.first_name }}</td>
          <td>{{ object.last_name }}</td>
            <td>
              <a class="btn btn-primary" href="{% url 'address_book:person-view' pk=object.pk %}">Просмотреть</a>
              <a class="btn btn-warning" href="{% url 'address_book:person-edit' pk=object.pk %}">Редактировать</a>
              <a class="btn btn-danger" href="{% url 'address_book:person-delete' pk=object.pk %}">Удалить</a>
            </td>
        </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% else %}
<div class="container w-50 mt-2">
  <a class="btn btn-outline-dark" href="{% url 'address_book:home'%}"><- Вернуться на главную страницу</a>
  <div class="table-responsive">
    <h2 class="text text-dark text-center mt-2 pb-2">Адресная книга</h2>
    <a class="btn btn-success mb-2 text " href="{% url 'address_book:person-create'  %}">Создать контакт</a>
    <h4 class="text text-dark text-center mt-2 pb-2">{{ message }}</h4>
  </div>
</div>
{% endif %}
{% endblock %}

address_book/templates/address_book/one_person.html
{% extends 'address_book/base.html' %}
{% block title %}
<title>{{ object.first_name}} {{ object.last_name}}</title>
{% endblock %}
{% block content %}
{% if object.pk %}
<a class="btn btn-outline-dark" href="{% url 'address_book:home'%}"><- Вернуться на главную страницу</a>
<div class="container pt-2 d-flex justify-content-center">
  <div class="card w-50 position-absolute border border-3
  border-secondary rounded bg-secondary text-white bg-gradient bg-opacity-75 text-center">
    <div class="card-body">
      <p>Имя: {{ object.first_name }}</p>
      <p>Фамилия: {{ object.last_name }}</p>
      <p>Страна: {{ object.country }}</p>
      <p>Город: {{ object.city }}</p>
      <p>Улица: {{ object.street }}</p>
      <p>URL-Адрес: {{ object.url_address }}</p>
      <p>Номер телефона: {{ object.phone_number }}</p>
      {% if object.image %}
      <img src="{{ object.image.url }}" alt="Картинки нет" width="150" height="150" >
      {% endif %}
    </div>
  </div>
</div>
{% else %}
<div class="container d-flex align-items-center flex-column justify-content-center text-center " style="height:100%">
  <div class="border border-rounded border-secondary border-3 p-3 bg-secondary">
    <p>{{ object }}</p>
    <a class="btn btn-outline-dark" href="{% url 'address_book:home'%}"><- Вернуться на главную страницу</a>
  </div>
</div>
{{ object }}
{% endif %}
{% endblock %}